# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ilk.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(586, 431)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 20, 541, 401))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.l1 = QtWidgets.QLabel(self.formLayoutWidget)
        self.l1.setObjectName("l1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.l1)
        self.txtUsername = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtUsername.setObjectName("txtUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtUsername)
        self.l2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.l2.setObjectName("l2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.l2)
        self.txtPass = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPass.setObjectName("txtPass")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtPass)
        self.bgiris = QtWidgets.QPushButton(self.formLayoutWidget)
        self.bgiris.setObjectName("bgiris")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bgiris)
        self.biptal = QtWidgets.QPushButton(self.formLayoutWidget)
        self.biptal.setObjectName("biptal")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.biptal)
        self.table = QtWidgets.QTableWidget(self.formLayoutWidget)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.table)
        self.l3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.l3.setText("")
        self.l3.setObjectName("l3")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.l3)
        self.cmb = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cmb.setObjectName("cmb")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.cmb)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.l1.setText(_translate("Dialog", "Kullanıcı Adı:"))
        self.l2.setText(_translate("Dialog", "Şifre:"))
        self.bgiris.setText(_translate("Dialog", "Giriş Yap"))
        self.biptal.setText(_translate("Dialog", "İptal"))
