# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ilk.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(551, 312)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 20, 501, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txtUserName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtUserName.setObjectName("txtUserName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtUserName)
        self.txtSifre = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtSifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtSifre.setObjectName("txtSifre")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtSifre)
        self.btnGiris = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnGiris.setObjectName("btnGiris")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btnGiris)
        self.btnIptal = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnIptal.setObjectName("btnIptal")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btnIptal)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 551, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Kullanıcı Adı:"))
        self.btnGiris.setText(_translate("MainWindow", "Giriş Yap"))
        self.btnIptal.setText(_translate("MainWindow", "İptal"))
        self.label_2.setText(_translate("MainWindow", "Şifre:"))
